# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('result', models.CharField(choices=[('good', 'Good'), ('try', 'Try')], default='good', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Six_slug', models.SlugField(max_length=250, unique_for_date='Six_date')),
                ('Six_number', models.CharField(max_length=100)),
                ('Six_date', models.DateTimeField()),
                ('Six_slave', models.CharField(max_length=30)),
                ('Six_master', models.CharField(max_length=10)),
                ('Six_oddSeve', models.CharField(max_length=10)),
                ('Six_bigSmall', models.CharField(max_length=10)),
                ('Six_He_oddSeve', models.CharField(max_length=10)),
                ('Six_He_bigSmall', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('-Six_date',),
            },
        ),
    ]
