# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 16:04
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='forecast',
            managers=[
                ('good_i', django.db.models.manager.Manager()),
            ],
        ),
    ]
