# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_auto_20171107_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Six_slug',
        ),
    ]
